### ISSUE TITLE
check unit tests succeed with GitHub actions.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/SpikeNetOpt.jl#11]
Github actions is currently configured to build, but I may not have yet triggered a unit test to run.

This file would need to executed inside GitHub actions: 

https://github.com/russelljjarvis/SpikeNetOpt.jl/blob/main/test/runtests.jl

Config file:
https://github.com/russelljjarvis/SpikeNetOpt.jl/blob/main/.github/workflows/ci.yml

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I'll do it.

**Comment by russelljjarvis** [comment]
Sure @mohitsaxenaknoldus  thanks!
@all-contributors please add @mohitsaxenaknoldus for issues, tests

**Comment by russelljjarvis** [comment]
Hi @mohitsaxenaknoldus,
I believe that the file
```
tests/test_izhi_model.jl
```
will pass unit tests.

**Comment by mohitsaxenaknoldus** [comment]
@russelljjarvis PR: https://github.com/russelljjarvis/SpikeNetOpt.jl/pull/16

**Comment by russelljjarvis** [comment]
@all-contributors please add @mohitsaxenaknoldus for tests
